name: pawfect
description: PawFect Balance App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.25
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.8
  shimmer: ^1.1.1
  lite_rolling_switch: ^0.1.1
  intl: ^0.16.1
  country_code_picker: ^1.4.0
  image_picker: ^0.6.7+4
  connectivity: ^0.4.9+2
  flutter_spinkit: ^4.1.2+1
  gallery_saver: ^2.0.1
    #  camera: ^0.5.8+5
  path: ^1.7.0
  http: ^0.12.2
  toggle_switch: ^0.1.8
  pie_chart: ^4.0.1
  fl_chart: ^0.11.1
  percent_indicator: ^2.1.6
  simple_animations: ^2.2.2
  package_info: ^0.4.3
  dio: ^3.0.10
  sqflite: ^1.3.2
  path_provider: ^1.6.22
  get_it: ^4.0.4
  progress_dialog: ^1.2.4
  mime: ^0.9.7
  http_parser: ^3.1.4
  flutter_image_compress: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo_front.png
    - assets/images/premium.png
    - assets/images/correct.png
    - assets/images/close.png
    - assets/images/logo_large.png
    - assets/images/logo_medium.png
    - assets/images/logo_small.png
    - assets/images/logo_new.png
    - assets/images/logo_name.png
    - assets/json/country.json
    - assets/json/dog_breed.json
    - assets/json/activity_level.json
    - assets/json/category.json
    - assets/json/daily_guides.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
    - family:  CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
